apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: create-myopenshiftblog-namespace
policyDefaults:
  remediationAction: enforce
  namespace: policies
  complianceType: musthave
  severity: medium
policies:
  - name: create-myopenshiftblog-namespace
    manifests:
      - path: myopenshiftblog-ns.yaml
